### ISSUE TITLE
MSDS Course Changes

### ISSUE THREAD

**Issue by piggjf** [MSCSHub/MSDSHub#1]
Just a heads up the algorithms course that was shared between MSCS and MSDS is being split.  Spring and Fall 2021 cohorts can still take the current algorithms class, but all other cohorts will only have the option to take the new course taught by Dr. Calvin Lin – DSC 395T Data Structures and Algorithms.  It is scheduled to be implemented in Spring 2022, so there’s time to update the hub.

Public details can be found here:  https://ms-datascience.utexas.edu/courses/data-structures

**Comment by EricPryzant** [comment]
Thanks for letting me know! I updated the site with the new course. In the future, could you please post issues on the MSCSHub repository? I mentioned on your issue over there that both sites actually use a single unified codebase and we use the MSCSHub repo as the main hub.
